version: '3.9'
services:
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: potion
